# Site settings
title: Girls Got Talent
email: contact@girlsgottalent.org
description: > # this means to ignore newlines until "baseurl:"
  Amazing stories, cool things, and everyday science - 
  fun for everyone, especially the girls!   Team Science is recruiting!
baseurl: "/gblog2" # the subpath of your site, e.g. /blog/
# url: "http://www.girlsgottalent.org" # the base hostname & protocol for your site
twitter_username: girlstalentpgh
github_username:  songela

gems: ['jekyll', 'jekyll-paginate', 'jekyll-categories', 'github-pages']
# Build settings
port: 3000
markdown: kramdown
permalink: /:year/:month/:title
paginate_path: "/blog/page:num/"
titlecase: true
paginate: 5